---
- name: this playbook is for install httpd packages
  hosts: webservers
  become: true
  tasks:
  - name: install packages
    yum:
      name: httpd
      state: installed
    notify: start httpd

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
