---
- name: this playbook is for install apache2
  hosts: appservers
  become: true
  tasks:
  - name: install apache2
    yum:
      name: apache2
      state: installed

  - name: start apache2
    service:
      name: apache2
      state: started
