---
- name: this playbook is for uninstall httpd packages
  hosts: webservers
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped

  - name: uninstall httpd
    yum:
      name: httpd
      state: removed


